version: "3.9"

services:
  db:
    image: mariadb:10.10.2
    volumes:
      - db-storage:/var/lib/mysql
    #restart: always
    ports:
      - 127.0.0.1:3306:3406
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    command: [ --default-authentication-plugin=mysql_native_password ]

  apiserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - photo-storage:/opt/photo-storage
    ports:
      - '8010:8010'
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: ../ajalbum2-viewer
      dockerfile: ./Dockerfile.nginx
    links:
      - apiserver
    ports:
      - '8020:8020'
    volumes:
      - photo-storage:/opt/photo-storage
    env_file:
      - .env

volumes:
  photo-storage:
  db-storage: